[package]
name = "languages"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true

[lints]
workspace = true
